-- =====================================================================
-- G3 Smoke-Test Fixture — TEARDOWN (idempotent, self-verifying)
-- =====================================================================
-- Removes the disposable GMC-G3-SMOKE project and every row created by
-- scripts/g3-smoke-fixture.seed.sql, plus any lifecycle rows produced
-- while testing (submissions, approvals, approval steps/events, workflow
-- events) and the audit rows generated by the delete triggers themselves.
--
-- Ordering matters:
--   * public.projects and public.approvals each carry an audit trigger, so
--     deleting them INSERTs fresh rows into audit_log. We therefore delete
--     those tables FIRST, then sweep audit_log LAST so no trigger-generated
--     row survives.
--   * audit_log has no audit trigger, so deleting from it does not recurse.
--
-- Safe to run multiple times. Fails loudly if anything is left behind.
-- =====================================================================

DO $$
DECLARE
  v_project uuid := 'aaaaaaaa-0000-4000-8000-000000000003';
  v_approval_ids uuid[];
  v_leftover integer;
BEGIN
  -- Collect approval ids tied to this fixture project (gate approvals use object_id = project id).
  SELECT array_agg(id) INTO v_approval_ids
  FROM public.approvals
  WHERE object_type = 'gate' AND object_id = v_project;

  -- Approval children first (FKs), then approvals (approvals has an audit trigger).
  IF v_approval_ids IS NOT NULL THEN
    DELETE FROM public.approval_events WHERE approval_id = ANY(v_approval_ids);
    DELETE FROM public.approval_steps  WHERE approval_id = ANY(v_approval_ids);
    DELETE FROM public.approvals       WHERE id         = ANY(v_approval_ids);
  END IF;

  -- Workflow events emitted by the gate lifecycle (metadata->>'project_id').
  DELETE FROM public.workflow_events WHERE metadata->>'project_id' = v_project::text;

  -- Remaining fixture/lifecycle rows scoped to the project.
  DELETE FROM public.gate_submissions WHERE project_id = v_project;
  DELETE FROM public.project_team     WHERE project_id = v_project;
  DELETE FROM public.document_files   WHERE project_id = v_project;
  DELETE FROM public.phase_gates      WHERE project_id = v_project;

  -- The project itself (this fires the projects audit trigger -> a delete row).
  DELETE FROM public.projects WHERE id = v_project;

  -- LAST: sweep every audit_log row that references this fixture project,
  -- including the delete rows just produced by the projects/approvals triggers.
  DELETE FROM public.audit_log WHERE record_id = v_project::text;

  RAISE NOTICE 'G3 smoke fixture torn down: project=%', v_project;

  -- ------------------------------------------------------------------
  -- Post-teardown assertions: every fixture row must be gone.
  -- ------------------------------------------------------------------
  SELECT
      (SELECT count(*) FROM public.projects          WHERE id = v_project)
    + (SELECT count(*) FROM public.phase_gates       WHERE project_id = v_project)
    + (SELECT count(*) FROM public.document_files    WHERE project_id = v_project)
    + (SELECT count(*) FROM public.project_team      WHERE project_id = v_project)
    + (SELECT count(*) FROM public.gate_submissions  WHERE project_id = v_project)
    + (SELECT count(*) FROM public.approvals         WHERE object_type = 'gate' AND object_id = v_project)
    + (SELECT count(*) FROM public.workflow_events   WHERE metadata->>'project_id' = v_project::text)
    + (SELECT count(*) FROM public.audit_log         WHERE record_id = v_project::text)
  INTO v_leftover;

  IF v_leftover <> 0 THEN
    RAISE EXCEPTION 'G3 teardown incomplete: % fixture rows remain for project %', v_leftover, v_project;
  END IF;

  RAISE NOTICE 'G3 smoke fixture teardown verified clean (0 rows remain).';
END $$;

-- Verification (should return 0):
--   SELECT count(*) FROM public.projects WHERE code = 'GMC-G3-SMOKE';
